# Generated by Django 5.2.1 on 2026-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_college_user_year_alter_domain_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='learning_resources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stage',
            name='practice_exercises',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
