# Generated by Django 5.2.1 on 2026-03-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_question_is_anonymous_question_upvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='is_accepted',
        ),
    ]
