# Generated by Django 5.2.1 on 2026-03-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_reply_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('senior', 'Senior')], default='student', max_length=20),
        ),
    ]
